apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    isDefault: true
    jsonData:
      host: 127.0.0.1
      port: 9327
      protocol: native
      username: grafana
      defaultDatabase: otel
    secureJsonData:
      password: $__file{secrets/clickhouse-grafana}
